openapi: 3.0.0
info:
  title: Vue Task Manager API
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: Logowanie użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Zwraca token JWT
  /api/auth/profile:
    get:
      summary: Pobierz profil zalogowanego użytkownika
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dane użytkownika
  /api/tasks:
    get:
      summary: Pobierz zadania
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista zadań
    post:
      summary: Dodaj zadanie
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '201':
          description: Zadanie dodane
  /api/tasks/{id}:
    delete:
      summary: Usuń zadanie
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Zadanie usunięte
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
